# BEGIN_KITTY_THEME
# ANSI 1987
include current-theme.conf
# END_KITTY_THEME

# Window
window_padding_width 10
remember_window_size no
background_opacity 100

# Font
font_size 14.0
# BEGIN_KITTY_FONTS
font_family      MapleMono
italic_font      auto
bold_font        auto
bold_italic_font auto
# END_KITTY_FONTS
