wallpaper {
    monitor = HDMI-A-1
    path = /home/user/65535/pictures/acgn/pixiv/焦茶-12845810/81754094_p0-0-canDie.jpg
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = /home/user/65535/pictures/acgn/pixiv/焦茶-12845810/81754094_p0-0-canDie.jpg
    fit_mode = cover
}